//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Endpoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Endpoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Endpoints", typeof(Endpoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-based page index (default 1).
        /// </summary>
        public static string ParamPage {
            get {
                return ResourceManager.GetString("ParamPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size 1–{0} (default {1}).
        /// </summary>
        public static string ParamPerPage {
            get {
                return ResourceManager.GetString("ParamPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok - Resource found and returned successfully.
        /// </summary>
        public static string Response200Ok {
            get {
                return ResourceManager.GetString("Response200Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok - The resource was successfully updated.
        /// </summary>
        public static string Response200OkUpdated {
            get {
                return ResourceManager.GetString("Response200OkUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created - The resource was successfully created.
        /// </summary>
        public static string Response201Created {
            get {
                return ResourceManager.GetString("Response201Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted - The resource was successfully deleted.
        /// </summary>
        public static string Response204Deleted {
            get {
                return ResourceManager.GetString("Response204Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request - The request is invalid or missing required fields.
        /// </summary>
        public static string Response400BadRequest {
            get {
                return ResourceManager.GetString("Response400BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found - The specified resource was not found.
        /// </summary>
        public static string Response404NotFound {
            get {
                return ResourceManager.GetString("Response404NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error - An unexpected error occurred on the server.
        /// </summary>
        public static string Response500InternalServerError {
            get {
                return ResourceManager.GetString("Response500InternalServerError", resourceCulture);
            }
        }
    }
}
