// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class ConstantEntities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // SQL Server cannot remove IDENTITY via AlterColumn — drop and recreate the tables.
            migrationBuilder.DropForeignKey(
                name: "FK_MarketDocument_MarketDocumentDirection_DirectionId",
                table: "MarketDocument");

            migrationBuilder.DropForeignKey(
                name: "FK_MarketDocument_MarketDocumentStatus_StatusId",
                table: "MarketDocument");

            migrationBuilder.DropTable(name: "MarketDocumentDirection");
            migrationBuilder.DropTable(name: "MarketDocumentStatus");

            migrationBuilder.CreateTable(
                name: "MarketDocumentDirection",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketDocumentDirection", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MarketDocumentStatus",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketDocumentStatus", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "MarketDocumentDirection",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Inbound" },
                    { 2, "Outbound" }
                });

            migrationBuilder.InsertData(
                table: "MarketDocumentStatus",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "New" },
                    { 2, "Done" },
                    { 3, "Error" }
                });

            migrationBuilder.AddForeignKey(
                name: "FK_MarketDocument_MarketDocumentDirection_DirectionId",
                table: "MarketDocument",
                column: "DirectionId",
                principalTable: "MarketDocumentDirection",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_MarketDocument_MarketDocumentStatus_StatusId",
                table: "MarketDocument",
                column: "StatusId",
                principalTable: "MarketDocumentStatus",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "MarketDocumentDirection",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "MarketDocumentDirection",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "MarketDocumentStatus",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "MarketDocumentStatus",
                keyColumn: "Id",
                keyValue: 2);

            migrationBuilder.DeleteData(
                table: "MarketDocumentStatus",
                keyColumn: "Id",
                keyValue: 3);

            migrationBuilder.DropForeignKey(
                name: "FK_MarketDocument_MarketDocumentDirection_DirectionId",
                table: "MarketDocument");

            migrationBuilder.DropForeignKey(
                name: "FK_MarketDocument_MarketDocumentStatus_StatusId",
                table: "MarketDocument");

            migrationBuilder.DropTable(name: "MarketDocumentDirection");
            migrationBuilder.DropTable(name: "MarketDocumentStatus");

            migrationBuilder.CreateTable(
                name: "MarketDocumentDirection",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketDocumentDirection", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "MarketDocumentStatus",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MarketDocumentStatus", x => x.Id);
                });

            migrationBuilder.AddForeignKey(
                name: "FK_MarketDocument_MarketDocumentDirection_DirectionId",
                table: "MarketDocument",
                column: "DirectionId",
                principalTable: "MarketDocumentDirection",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_MarketDocument_MarketDocumentStatus_StatusId",
                table: "MarketDocument",
                column: "StatusId",
                principalTable: "MarketDocumentStatus",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
