// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class ConnectorRefactor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ConfigurationIntegration");

            migrationBuilder.DropTable(
                name: "SystemIntegrationField");

            migrationBuilder.DropTable(
                name: "SystemIntegration");

            migrationBuilder.DropTable(
                name: "IntegrationImplementation");

            migrationBuilder.CreateTable(
                name: "ConnectorImplementation",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConnectorImplementation", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ConnectorType",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConnectorType", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Connector",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    Description = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ConnectorTypeId = table.Column<int>(type: "int", nullable: false),
                    ConnectorImplementationId = table.Column<int>(type: "int", nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Connector", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Connector_ConnectorImplementation_ConnectorImplementationId",
                        column: x => x.ConnectorImplementationId,
                        principalTable: "ConnectorImplementation",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Connector_ConnectorType_ConnectorTypeId",
                        column: x => x.ConnectorTypeId,
                        principalTable: "ConnectorType",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ConfigurationConnector",
                columns: table => new
                {
                    ConfigurationsId = table.Column<int>(type: "int", nullable: false),
                    ConnectorsId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConfigurationConnector", x => new { x.ConfigurationsId, x.ConnectorsId });
                    table.ForeignKey(
                        name: "FK_ConfigurationConnector_Configuration_ConfigurationsId",
                        column: x => x.ConfigurationsId,
                        principalTable: "Configuration",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ConfigurationConnector_Connector_ConnectorsId",
                        column: x => x.ConnectorsId,
                        principalTable: "Connector",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ConnectorField",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ConnectorId = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    Value = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    IsSecret = table.Column<bool>(type: "bit", nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConnectorField", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ConnectorField_Connector_ConnectorId",
                        column: x => x.ConnectorId,
                        principalTable: "Connector",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ConfigurationConnector_ConnectorsId",
                table: "ConfigurationConnector",
                column: "ConnectorsId");

            migrationBuilder.CreateIndex(
                name: "IX_Connector_ConnectorImplementationId",
                table: "Connector",
                column: "ConnectorImplementationId");

            migrationBuilder.CreateIndex(
                name: "IX_Connector_ConnectorTypeId",
                table: "Connector",
                column: "ConnectorTypeId");

            migrationBuilder.CreateIndex(
                name: "IX_ConnectorField_ConnectorId",
                table: "ConnectorField",
                column: "ConnectorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ConfigurationConnector");

            migrationBuilder.DropTable(
                name: "ConnectorField");

            migrationBuilder.DropTable(
                name: "Connector");

            migrationBuilder.DropTable(
                name: "ConnectorImplementation");

            migrationBuilder.DropTable(
                name: "ConnectorType");

            migrationBuilder.CreateTable(
                name: "IntegrationImplementation",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IntegrationImplementation", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SystemIntegration",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IntegrationImplementationId = table.Column<int>(type: "int", nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Description = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SystemIntegration", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SystemIntegration_IntegrationImplementation_IntegrationImplementationId",
                        column: x => x.IntegrationImplementationId,
                        principalTable: "IntegrationImplementation",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ConfigurationIntegration",
                columns: table => new
                {
                    ConfigurationsId = table.Column<int>(type: "int", nullable: false),
                    IntegrationsId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ConfigurationIntegration", x => new { x.ConfigurationsId, x.IntegrationsId });
                    table.ForeignKey(
                        name: "FK_ConfigurationIntegration_Configuration_ConfigurationsId",
                        column: x => x.ConfigurationsId,
                        principalTable: "Configuration",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_ConfigurationIntegration_SystemIntegration_IntegrationsId",
                        column: x => x.IntegrationsId,
                        principalTable: "SystemIntegration",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SystemIntegrationField",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IntegrationId = table.Column<int>(type: "int", nullable: false),
                    CreatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    IsSecret = table.Column<bool>(type: "bit", nullable: false),
                    LastModifiedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    Value = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SystemIntegrationField", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SystemIntegrationField_SystemIntegration_IntegrationId",
                        column: x => x.IntegrationId,
                        principalTable: "SystemIntegration",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_ConfigurationIntegration_IntegrationsId",
                table: "ConfigurationIntegration",
                column: "IntegrationsId");

            migrationBuilder.CreateIndex(
                name: "IX_SystemIntegration_IntegrationImplementationId",
                table: "SystemIntegration",
                column: "IntegrationImplementationId");

            migrationBuilder.CreateIndex(
                name: "IX_SystemIntegrationField_IntegrationId",
                table: "SystemIntegrationField",
                column: "IntegrationId");
        }
    }
}
