// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AuditableEntityUtc : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "LastModifiedAt",
                table: "User",
                newName: "LastModifiedAtUtc");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                table: "User",
                newName: "CreatedAtUtc");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAt",
                table: "Role",
                newName: "LastModifiedAtUtc");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                table: "Role",
                newName: "CreatedAtUtc");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAt",
                table: "Permission",
                newName: "LastModifiedAtUtc");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                table: "Permission",
                newName: "CreatedAtUtc");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAt",
                table: "Module",
                newName: "LastModifiedAtUtc");

            migrationBuilder.RenameColumn(
                name: "CreatedAt",
                table: "Module",
                newName: "CreatedAtUtc");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "LastModifiedAtUtc",
                table: "User",
                newName: "LastModifiedAt");

            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                table: "User",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAtUtc",
                table: "Role",
                newName: "LastModifiedAt");

            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                table: "Role",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAtUtc",
                table: "Permission",
                newName: "LastModifiedAt");

            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                table: "Permission",
                newName: "CreatedAt");

            migrationBuilder.RenameColumn(
                name: "LastModifiedAtUtc",
                table: "Module",
                newName: "LastModifiedAt");

            migrationBuilder.RenameColumn(
                name: "CreatedAtUtc",
                table: "Module",
                newName: "CreatedAt");
        }
    }
}
