// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924004055_AddPermissionModule")]
    partial class AddPermissionModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConfigurationConnector", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.HasKey("ConfigurationId", "ConnectorId");

                    b.HasIndex("ConnectorId");

                    b.ToTable("ConfigurationConnector", (string)null);
                });

            modelBuilder.Entity("Core.Market.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Market");
                });

            modelBuilder.Entity("Core.Market.MarketDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DirectionId");

                    b.HasIndex("StatusId");

                    b.ToTable("MarketDocument");
                });

            modelBuilder.Entity("Core.Market.MarketDocumentDirection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("MarketDocumentDirection");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Inbound"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Outbound"
                        });
                });

            modelBuilder.Entity("Core.Market.MarketDocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("MarketDocumentStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Done"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Error"
                        });
                });

            modelBuilder.Entity("Core.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Allows viewing users.",
                            ModuleId = 1,
                            Name = "users.read"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Allows creating, updating, and deleting users.",
                            ModuleId = 1,
                            Name = "users.write"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Allows viewing roles.",
                            ModuleId = 1,
                            Name = "roles.read"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Allows creating, updating, and deleting roles.",
                            ModuleId = 1,
                            Name = "roles.write"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Allows viewing permissions.",
                            ModuleId = 1,
                            Name = "permissions.read"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Allows creating, updating, and deleting permissions.",
                            ModuleId = 1,
                            Name = "permissions.write"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Allows viewing connectors.",
                            ModuleId = 2,
                            Name = "connectors.read"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Allows creating, updating, and deleting connectors.",
                            ModuleId = 2,
                            Name = "connectors.write"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Allows viewing companies.",
                            ModuleId = 2,
                            Name = "companies.read"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Allows creating, updating, and deleting companies.",
                            ModuleId = 2,
                            Name = "companies.write"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Allows viewing markets.",
                            ModuleId = 2,
                            Name = "markets.read"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Allows creating, updating, and deleting markets.",
                            ModuleId = 2,
                            Name = "markets.write"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Allows viewing configurations.",
                            ModuleId = 2,
                            Name = "configurations.read"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Allows creating, updating, and deleting configurations.",
                            ModuleId = 2,
                            Name = "configurations.write"
                        });
                });

            modelBuilder.Entity("Core.Security.PermissionModule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("PermissionModule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Settings"
                        });
                });

            modelBuilder.Entity("Core.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Core.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Core.Shared.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Core.Shared.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigurationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ConfigurationTypeId");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Core.Shared.ConfigurationField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("ConfigurationField");
                });

            modelBuilder.Entity("Core.Shared.ConfigurationType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ConfigurationType");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "EDI Import"
                        });
                });

            modelBuilder.Entity("Core.Shared.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectorImplementationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorImplementationId");

                    b.ToTable("Connector");
                });

            modelBuilder.Entity("Core.Shared.ConnectorField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.ToTable("ConnectorField");
                });

            modelBuilder.Entity("Core.Shared.ConnectorImplementation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorTypeId");

                    b.ToTable("ConnectorImplementation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectorTypeId = 1,
                            Description = "FTP connector implementation backed by FluentFTP.",
                            Identifier = "FluentFtpService",
                            Name = "Fluent FTP"
                        },
                        new
                        {
                            Id = 2,
                            ConnectorTypeId = 1,
                            Description = "SFTP connector implementation backed by SSH.NET.",
                            Identifier = "SshNetSftpService",
                            Name = "SSH.NET SFTP"
                        },
                        new
                        {
                            Id = 3,
                            ConnectorTypeId = 1,
                            Description = "Local drop-folder stand-in for FTP/SFTP, for development use only.",
                            Identifier = "LocalFileSystemFtpService",
                            Name = "Local File System FTP"
                        },
                        new
                        {
                            Id = 4,
                            ConnectorTypeId = 2,
                            Description = "File storage connector implementation backed by Azure Blob Storage.",
                            Identifier = "AzureBlobFileStorage",
                            Name = "Azure Blob Storage"
                        },
                        new
                        {
                            Id = 5,
                            ConnectorTypeId = 2,
                            Description = "Local file system stand-in for file storage, for development use only.",
                            Identifier = "LocalFileSystemFileStorage",
                            Name = "Local File System Storage"
                        });
                });

            modelBuilder.Entity("Core.Shared.ConnectorType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("ConnectorType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "FTP/SFTP file transfer connector.",
                            Name = "FTP"
                        },
                        new
                        {
                            Id = 2,
                            Description = "File storage connector.",
                            Name = "File Storage"
                        });
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("ConfigurationConnector", b =>
                {
                    b.HasOne("Core.Shared.Configuration", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Shared.Connector", null)
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Market.MarketDocument", b =>
                {
                    b.HasOne("Core.Shared.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Market.MarketDocumentDirection", "Direction")
                        .WithMany()
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Market.MarketDocumentStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Direction");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Core.Security.Permission", b =>
                {
                    b.HasOne("Core.Security.PermissionModule", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Core.Shared.Company", b =>
                {
                    b.HasOne("Core.Market.Market", "Market")
                        .WithMany("Companies")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Market");
                });

            modelBuilder.Entity("Core.Shared.Configuration", b =>
                {
                    b.HasOne("Core.Shared.Company", "Company")
                        .WithMany("Configurations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Shared.ConfigurationType", "ConfigurationType")
                        .WithMany("Configurations")
                        .HasForeignKey("ConfigurationTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ConfigurationType");
                });

            modelBuilder.Entity("Core.Shared.ConfigurationField", b =>
                {
                    b.HasOne("Core.Shared.Configuration", "Configuration")
                        .WithMany("ConfigurationFields")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("Core.Shared.Connector", b =>
                {
                    b.HasOne("Core.Shared.ConnectorImplementation", "ConnectorImplementation")
                        .WithMany("Connectors")
                        .HasForeignKey("ConnectorImplementationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConnectorImplementation");
                });

            modelBuilder.Entity("Core.Shared.ConnectorField", b =>
                {
                    b.HasOne("Core.Shared.Connector", "Connector")
                        .WithMany("ConnectorFields")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("Core.Shared.ConnectorImplementation", b =>
                {
                    b.HasOne("Core.Shared.ConnectorType", "ConnectorType")
                        .WithMany("ConnectorImplementations")
                        .HasForeignKey("ConnectorTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConnectorType");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("Core.Security.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("Core.Security.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Market.Market", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Core.Security.PermissionModule", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Core.Shared.Company", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Core.Shared.Configuration", b =>
                {
                    b.Navigation("ConfigurationFields");
                });

            modelBuilder.Entity("Core.Shared.ConfigurationType", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Core.Shared.Connector", b =>
                {
                    b.Navigation("ConnectorFields");
                });

            modelBuilder.Entity("Core.Shared.ConnectorImplementation", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("Core.Shared.ConnectorType", b =>
                {
                    b.Navigation("ConnectorImplementations");
                });
#pragma warning restore 612, 618
        }
    }
}
