// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class NoActionModulePermissionDelete : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Permission_Module_ModuleId",
                table: "Permission");

            migrationBuilder.AddForeignKey(
                name: "FK_Permission_Module_ModuleId",
                table: "Permission",
                column: "ModuleId",
                principalTable: "Module",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Permission_Module_ModuleId",
                table: "Permission");

            migrationBuilder.AddForeignKey(
                name: "FK_Permission_Module_ModuleId",
                table: "Permission",
                column: "ModuleId",
                principalTable: "Module",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
