// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class MarketEntity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "MarketId",
                table: "Company",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Market",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    Identifier = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false),
                    TimeZoneId = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Market", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Company_MarketId",
                table: "Company",
                column: "MarketId");

            migrationBuilder.AddForeignKey(
                name: "FK_Company_Market_MarketId",
                table: "Company",
                column: "MarketId",
                principalTable: "Market",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Company_Market_MarketId",
                table: "Company");

            migrationBuilder.DropTable(
                name: "Market");

            migrationBuilder.DropIndex(
                name: "IX_Company_MarketId",
                table: "Company");

            migrationBuilder.DropColumn(
                name: "MarketId",
                table: "Company");
        }
    }
}
