name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

env:
  AZURE_WEBAPP_NAME: ovenbird-api
  AZURE_WEBAPP_PACKAGE_PATH: './src/Web/publish'
  DOTNET_VERSION: '10.x'
  SOLUTION_PATH: 'Ovenbird.slnx'
  API_PROJECT_PATH: 'src/Web/Web.csproj'
  PUBLISH_DIR: './publish'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/webapi

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: webapi
          path: ${{env.DOTNET_ROOT}}/webapi

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v5
        with:
          name: webapi

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEB_API_DEPLOY_TOKEN }}
          package: .