name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  workflow_dispatch:
    
defaults:
  run:
    working-directory: frontend

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: frontend/package.json

      - name: Install node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: NODE_OPTIONS="--max-old-space-size=6144" pnpm run build

      - name: Prepare artifact
        run: |
          cp package.json .output/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ovenbird-app
          publish-profile: ${{ secrets.AZURE_WEB_APP_DEPLOY_TOKEN }}
          package: .output